name: CI
on:
  issues:
    types: [opened, edited, milestoned]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: hmarr/debug-action@v2
      - name: Run LABELS- ${{ github.event.issue.labels.*.name }}  - ${{ contains(github.event.issue.labels.*.name, 'RFC')}}
        run: echo ${{ github.event.issue.labels.*.name }} 
        

              
