

name: CI


on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    types:
      - opened
      - edited
      - reopened
      - labeled
      - unlabeled
      - synchronize
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallels
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          #X: gh pr view ${{ github.event.pull_request.number }} --json labels
        run: |
          echo "${{ toJson(github.event.pull_request.labels) }}"  
          
