

name: CI


on:
  issues:
    types: [opened, edited, milestoned]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo ${{ github.event }}
      - name: Run a one-line script
        run: echo ${{ fromJSON(github.event) }}
      - name: Run a one-line script
        run: echo ${{ fromJSON(github.event.issues) }}
      - name: Run a one-line script
        run: echo ${{ github.event.issues }}



          
