name: ci

on: pull_request

jobs:
  set-matrix:
    name: Configure matrix for gradle modules
    runs-on: [ default ]
    outputs:
      matrix: ${{ steps.set_modules.outputs.matrix }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - id: set_modules
        shell: bash
        working-directory: ./.github/config
        run: |
          set -Exeuo pipefail
          content=$(tr '\n\r' ' ' < deployments)
          echo "matrix=$content" >> "$GITHUB_OUTPUT"
  
  deploy-gradle-modules:
    needs:
      - set-matrix
    name: Release and Deploy "${{ matrix.config.module }}"
    runs-on: [ default ]
    timeout-minutes: 10
    concurrency: ${{ matrix.config.module }}
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.set-matrix.outputs.matrix) }}

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - id: set_modules
        shell: bash
        working-directory: ./.github/config
        run: |
          set -Exeuo pipefail
          echo "${{ matrix.config.module }}"
