name: Read from json file
on:
  push:
    branches:
      - main

jobs:
  read-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Read Values from JSON
        id: set_modules
        shell: bash
        working-directory: ./.github
        run: |
          set -Exeuo pipefail
          content=$(tr '\n\r' ' ' < deploy)
          echo "matrix=$content" >> "$GITHUB_OUTPUT"

  print-values:
    needs: read-json
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.read-json.outputs.matrix) }}
    steps:
      - name: Read the output from ${{ matrix.config.module }}
        run: gradle :${{ matrix.config.module }}:jib       

  # print-values:
  #   needs: read-json
  #   runs-on: ubuntu-latest
    # strategy:
    #   fail-fast: false
    #   matrix: ${{ fromJson(needs.read-json.outputs.matrix) }}
    # steps:
    #  - name: Read the output from job1
    #    run: |
    #       output_from_job1="${{ fromJson(needs.read-json.outputs.matrix) }}"
    #       echo "Output from job1: $output_from_job1"
    #   - name: Print Gradle and Module Values
    #     run: |
    #       echo "Gradle value: ${{ matrix.config }}"
    #       # Get the values from the previous job's outputs
    #       gradle=$([[ "${{ matrix.config.gradle }}" == "null" ]] && echo "Gradle not found" || echo "${{ matrix.config.gradle }}")
    #       module=$([[ "${{ matrix.config.module }}" == "null" ]] && echo "Module not found" || echo "${{ matrix.config.module }}")

    #       # Print the extracted values
    #       echo "Gradle value: $gradle"
    #       echo "Module value: $module"
